In [7]:
import numpy as np
matrixA = np.array([ [4,6,6], [9,3,5] ])
matrixB = np.array([ [6,2], [3,5], [8,1] ])
dotproduct = matrixA.dot(matrixB)
print("Matrix A:\n", matrixA, "\n Matrix B:\n", matrixB, "\n Result:\n", dotproduct)

Matrix A:
 [[4 6 6]
 [9 3 5]] 
 Matrix B:
 [[6 2]
 [3 5]
 [8 1]] 
 Result:
 [[ 90  44]
 [103  38]]
