In [3]:
import numpy as np
matrix1=[[1,2,3],
        [4,5,6],
        [7,8,9]]

matrix2=[[9,8,7],
       [6,5,4],
       [3,2,1]]

mat1=np.array(matrix1)
mat2=np.array(matrix2)
result = np.dot(mat1,mat2)
print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
