In [1]:
import numpy as np
import pandas as pd
import statistics as stat 
data = pd.read_csv('Assignment_11_Salary_Data.csv')

In [2]:
data

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [3]:
data[['YearsExperience']][0:5]

YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [4]:
data.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [5]:
data.describe().mean()

YearsExperience        8.168903
Salary             60758.991223
dtype: float64

In [6]:
print("Mean YearsExperience : ", data['YearsExperience'].describe().mean() )
print("Mean Salary : ", data['Salary'].describe().mean() )
print("\n")
print("Median YearsExperience : ",np.median(data['YearsExperience']))
print("Median Salary : ",np.median(data['Salary']))
print("\n")
print("Mode YearsExperience : ",stat.mode(data['YearsExperience']))
print("Mode Salary : ",stat.mode(data['Salary']))
print("\n")
print("Standard Deviation YearsExperience  : ", data['YearsExperience'].describe().std())
print("Standard Deviation Salary  : ", data['Salary'].describe().std())

Mean YearsExperience :  8.168902686374508
Mean Salary :  60758.991223072786


Median YearsExperience :  4.7
Median Salary :  65237.0


Mode YearsExperience :  3.2
Mode Salary :  39343.0


Standard Deviation YearsExperience  :  9.30067087834344
Standard Deviation Salary  :  39605.7524645371


In [7]:
print("YearsExperience Correlation Coefficient: ", np.corrcoef(data['YearsExperience']))
print("Salary Correlation Coefficient: ", np.corrcoef(data['Salary']))

YearsExperience Correlation Coefficient:  1.0
Salary Correlation Coefficient:  1.0


In [8]:
#If you don't transpose the 2d array, the method interprets row as vector, so in your first few cases,
#it calculates the correlation coefficients of all the combinations of the rows, since each row is length 2 vector,
#you get all 1 as coefficients, which would happen when you try to fit a line with two points (always perfect fit).
#src:
#    https://stackoverflow.com/questions/44333504/np-corrcoef-behavior-with-pandas-dataframes

print("YearsExperience/Salary Correlation Coefficient of first 10 entries: \n") 
np.corrcoef(data[['YearsExperience','Salary']])

YearsExperience/Salary Correlation Coefficient of first 10 entries: 



array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1

In [9]:
data.T

0        1        2        3        4        5   \
YearsExperience      1.1      1.3      1.5      2.0      2.2      2.9   
Salary           39343.0  46205.0  37731.0  43525.0  39891.0  56642.0   

                      6        7        8        9   ...       20       21  \
YearsExperience      3.0      3.2      3.2      3.7  ...      6.8      7.1   
Salary           60150.0  54445.0  64445.0  57189.0  ...  91738.0  98273.0   

                       22        23        24        25        26        27  \
YearsExperience       7.9       8.2       8.7       9.0       9.5       9.6   
Salary           101302.0  113812.0  109431.0  105582.0  116969.0  112635.0   

                       28        29  
YearsExperience      10.3      10.5  
Salary           122391.0  121872.0  

[2 rows x 30 columns]

In [10]:
print("YearsExperience/Salary Correlation Coefficient of all entries: \n") 
np.corrcoef(data.T)

YearsExperience/Salary Correlation Coefficient of all entries: 



array([[1.        , 0.97824162],
       [0.97824162, 1.        ]])

In [11]:
data[0:10].T

0        1        2        3        4        5  \
YearsExperience      1.1      1.3      1.5      2.0      2.2      2.9   
Salary           39343.0  46205.0  37731.0  43525.0  39891.0  56642.0   

                       6        7        8        9  
YearsExperience      3.0      3.2      3.2      3.7  
Salary           60150.0  54445.0  64445.0  57189.0

In [12]:
print("YearsExperience/Salary Correlation Coefficient of first 10 entries: \n") 
np.corrcoef(data[0:10].T)

YearsExperience/Salary Correlation Coefficient of first 10 entries: 



array([[1.        , 0.84680069],
       [0.84680069, 1.        ]])