In [42]:
# 1- In ‘Course_page_actions.csv’ dataset
# Test The Enrollment Rate in each group snd get the
# Alternative then test it
# Enrollment Rate for Ex:
# (For Experiment Group )( Experiment.action==’enroll’/
# Experiment.action==’view’)

In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [44]:
data = pd.read_csv("course_page_actions.csv")

In [45]:
#data = data.drop_duplicates(subset = 'id',keep= 'first')

In [46]:
data.head()

timestamp      id       group action    duration
0  2016-09-24 17:14:52.012145  261869  experiment   view  130.545004
1  2016-09-24 18:45:09.645857  226546  experiment   view  159.862440
2  2016-09-24 19:16:21.002533  286353  experiment   view   79.349315
3  2016-09-24 19:43:06.927785  842279  experiment   view   55.536126
4  2016-09-24 21:08:22.790333  781883  experiment   view  204.322437

# 1)Test The Enrollment Rate in each group #

In [53]:
data.group.unique()

array(['experiment', 'control'], dtype=object)

In [54]:
exp_enrolled = data.query("group == 'experiment' and action == 'enroll'")
exp = data.query("group == 'experiment' and action == 'view'")
exp_enrolled.head()

timestamp      id       group  action    duration
137   2016-09-28 02:08:53.050942  711838  experiment  enroll  201.785800
602   2016-10-10 11:30:33.838974  576318  experiment  enroll  176.921806
966   2016-10-21 20:18:42.363288  724590  experiment  enroll   99.759691
1008  2016-10-23 03:05:45.425012  314669  experiment  enroll   65.266778
1062  2016-10-24 13:30:25.843971  449244  experiment  enroll   61.008083

In [55]:
exp_enrollment_rate = exp_enrolled.shape[0] / exp.shape[0]
exp_enrollment_rate

0.007696007696007696

In [56]:
ctrl_enrolled = data.query("group == 'control' and action == 'enroll'")
ctrl = data.query("group == 'control' and action == 'view'")
ctrl_enrolled.head()

timestamp      id    group  action  duration
7    2016-09-24 22:43:35.119748  701620  control  enroll       NaN
222  2016-09-30 11:57:44.059162  802405  control  enroll       NaN
231  2016-09-30 17:17:07.708962  524941  control  enroll       NaN
256  2016-10-01 08:40:31.380072  381758  control  enroll       NaN
362  2016-10-03 20:08:57.011373  757165  control  enroll       NaN

In [57]:
ctrl_enrollment_rate = ctrl_enrolled.shape[0] / ctrl.shape[0]
ctrl_enrollment_rate

0.012827090815802977

# Observable Difference #

In [58]:
obs_difference = exp_enrollment_rate - ctrl_enrollment_rate
obs_difference

-0.00513108311979528

# Hypothesis #

### Null Hypothesis: group 'experiment' enrollment rate is bigger than group 'control' enrollment rate ###
##### Null Hypothesis: experiment_enrollment_rate - control_enrollment_rate > 0 ####
### Alternative Hypothesis: group 'experiment' enrollment rate is smaller than or equal group ' control' enrollment rate ###
##### Alternative Hypothesis: experiment_enrollment_rate - control_enrollment_rate <= 0 ####


# 1)Gather Data #

In [59]:
difference = []
for _ in range(2000):
    sample = data.sample(data.shape[0],replace = True)
    exp_enrolled = sample.query("group == 'experiment' and action == 'enroll'")
    exp = sample.query("group == 'experiment' and action == 'view'")
    exp_enrollment_rate = exp_enrolled.shape[0] / exp.shape[0]
    ctrl_enrolled = sample.query("group == 'control' and action == 'enroll'")
    ctrl = sample.query("group == 'control' and action == 'view'")
    ctrl_enrollment_rate = ctrl_enrolled.shape[0] / ctrl.shape[0]
    difference.append(exp_enrollment_rate - ctrl_enrollment_rate)

In [60]:
plt.hist(difference)

(array([  6.,  57., 273., 607., 656., 325.,  71.,   4.,   0.,   1.]),
 array([-0.0170371 , -0.01411217, -0.01118723, -0.0082623 , -0.00533736,
        -0.00241243,  0.00051251,  0.00343744,  0.00636237,  0.00928731,
         0.01221224]),
 <BarContainer object of 10 artists>)

# 2)Create Null popluation #

In [61]:
difference = np.array(difference)
normal = np.random.normal(0,difference.std(),difference.shape[0])
plt.hist(normal)

(array([  3.,  30., 105., 277., 414., 473., 425., 187.,  69.,  17.]),
 array([-0.01097077, -0.00890351, -0.00683624, -0.00476898, -0.00270171,
        -0.00063445,  0.00143282,  0.00350008,  0.00556735,  0.00763461,
         0.00970188]),
 <BarContainer object of 10 artists>)

In [62]:
plt.hist(normal)
plt.axvline(obs_difference, c= 'red')

In [63]:
(normal<obs_difference).mean()

0.0555

# Conclusion: Alternative Hypothesis Rejected, Maintain current status #
#### group 'experiment' enrollment rate is bigger than group 'control' enrollment rate ###