In [1]:
import numpy as np
# two dimensional arrays
m1 = np.array([[1,4,7],[2,5,8]])
m2 = np.array([[1,4],[2,5],[3,6]])
m3 = np.dot(m1,m2) 
print(m3) 

# three dimensional arrays
m1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
m2 = ([3, 4, 6],[5, 6, 7],[6,56, 7]) 
m3 = np.dot(m1,m2) 
print(m3) 

[[30 66]
 [36 81]]
[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]
