In [2]:
import numpy as np
matrix1 = np.array([[3,5,7],[1,7,4],[4,9,50]])
matrix2 = np.array([[5,8,1],[4,8,3],[1,8,20]])
matrix3 = np.dot(matrix1,matrix2) 
print(matrix3)

[[  42  120  158]
 [  37   96  102]
 [ 106  504 1031]]
