In [1]:
import numpy as np

matrix1 = np.array([[2,5,8],[3,9,2],[6,6,20]])
matrix2 = np.array([[1,4,3],[2,5,1],[3,6,10]])
matrix3 = np.dot(matrix1,matrix2) 
print(matrix3)


[[ 36  81  91]
 [ 27  69  38]
 [ 78 174 224]]
